// <auto-generated />
using System;
using GestorTaller.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestorTaller.Datos.Migrations
{
    [DbContext(typeof(GestorTallerDbContext))]
    partial class GestorTallerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestorTaller.Negocio.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("GestorTaller.Negocio.HistorialEstadoOrden", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<Guid>("OrdenId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrdenPosicion")
                        .HasColumnType("integer")
                        .HasColumnName("orden_posicion");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.ToTable("orden_historial_estado", (string)null);
                });

            modelBuilder.Entity("GestorTaller.Negocio.Orden", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<decimal>("CostoDiagnostico")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_diagnostico");

                    b.Property<bool>("CotizacionAceptada")
                        .HasColumnType("boolean")
                        .HasColumnName("cotizacion_aceptada");

                    b.Property<string>("DescripcionObjeto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion_objeto");

                    b.Property<string>("DescripcionProblema")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion_problema");

                    b.Property<string>("DetalleDiagnostico")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detalle_diagnostico");

                    b.Property<string>("DetalleReparacion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detalle_reparacion");

                    b.Property<string>("EmpleadoCotizacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("empleado_cotizacion");

                    b.Property<string>("EmpleadoDiagnostico")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("empleado_diagnostico");

                    b.Property<string>("EmpleadoEntrega")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("empleado_entrega");

                    b.Property<string>("EmpleadoReparacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("empleado_reparacion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_entrega");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_recepcion");

                    b.Property<decimal>("MontoCotizado")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto_cotizado");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto_pagado");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("orden", (string)null);
                });

            modelBuilder.Entity("GestorTaller.Negocio.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contrasena");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("GestorTaller.Negocio.HistorialEstadoOrden", b =>
                {
                    b.HasOne("GestorTaller.Negocio.Orden", null)
                        .WithMany()
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestorTaller.Negocio.Orden", b =>
                {
                    b.HasOne("GestorTaller.Negocio.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
